post http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "otrousuario",
  "password": "sehsdfsfi",
  "name": "otro usuario"
}

###
get http://localhost:3003/api/users