delete http://localhost:3003/api/blogs/666f8c67a552c7c2e540e6dd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im90cm91c3VhcmlvIiwiaWQiOiI2NjZjYmQ2YTMyOTM4OGZjM2NlM2VlM2MiLCJpYXQiOjE3MTg0NzY1NDJ9.CUuJU1hUalDbJ79H_jqDbXBk2ZhUOjfygg58rERgdkU